### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by meetbryce** [bwin/gulp-asar#3]
I'm running OS X El Capitan `v10.11` + Node `v4.1.2` + npm `v2.14.4` and am receiving the following error:

```
1 error generated.
make: *** [Release/obj.target/native_mate/node_modules/native-mate/vendor/src/native_mate/arguments.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/meetbryce/Dropbox/Code/Projects/ScotchIO/githubElectron/node_modules/gulp-asar/node_modules/asar/node_modules/chromium-pickle
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "gulp-asar@0.0.2"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! chromium-pickle@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromium-pickle@0.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the chromium-pickle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromium-pickle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/...../npm-debug.log
```

**Comment by Eusebius1920** [comment]
+1 Same here on OS X Yosemite

**Comment by dotorify** [comment]
+1 Me too, I'm running Same OS X El Capitan + Node v5.3.0
